### PR TITLE
Add german translations

### PR DESCRIPTION
**Pull request by tzeumer**
Add translations for german. Took some notes in CHANGELOG.md in the language folder.

### CODE REVIEW

**Comment by ssborbis** [comment]
If Quick Menu sounds weird, rename it at your discretion. I'm not committed to any of the terms I use. 

I'll add css classes as needed to customize the formatting

**Comment by tzeumer** [comment]
Quick Menu is fine. I meant my translation "Schnellmenü" sound weird and maybe it shouldn't be translated at all - I just mentioned it in the readme so another possible translator wouldn't feel compelled to stick to my choice :)

**Comment by ssborbis** [comment]
It doesn't need to be a literal translation. Feel free to take liberties with the terms and use whatever you think sounds best. Thanks for doing this.

**Comment by hg42** [comment]
I use english language because of it's compactness.
But I think "Schnellmenü" is ok.
Eventually you could take "Schnellzugriffs-Menü" (a bit too long, but clearly indicating what it is)
or "Direkt-Menü"?

**Comment by tzeumer** [comment]
@hg42 When possible I use programs in their native language, too. I fetched the german developer edition just for this spontaneous Sunday undertaking. Maybe it convinces some people who are "afraid" of English to use this fine addon :)

**Comment by hg42** [comment]
yes, it's one of my most useful extensions (used 1000 times each day).

**Pull request merged**
