### PR TITLE
French messages.json for version 1.42

### PR DESCRIPTION
**Pull request by DenB10**
Dear Mike,
I try to keep the French translation up to date but I am surprised that it is not up to date when the next version is published on AMO. Is it an oversight on your part or an error in the publication?
Let me know if you are still interested in the French translation of your extension.
Best regards,
Denis

### CODE REVIEW

**Comment by ssborbis** [comment]
Hmm... I'm sure I merged it. I must not have pulled it to my local repo before building the release.

As always, I appreciate your contributions. I'll get a minor release up soon.

**Comment by DenB10** [comment]
And this is still the case for version 1.42.1.
Although I read on AMO: "fix: missing French translations ( DenB10 )", translations are still not up to date on AMO!!!
Sorry, I think your local repo is not updated...

**Comment by DenB10** [comment]
[cs_fr_messages.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/9331669/cs_fr_messages.zip)

**Comment by ssborbis** [comment]
Ah, I see what's happening. I'm merging your updates to the master, but building from the development, so my local pull doesn't get the changes. I'm pretty sure I've got it now. 1.42.2 going up soon.

**Pull request merged**
