### PR TITLE
update for cs 1.32.6

### PR DESCRIPTION
**Pull request by DenB10**
I completely revised the French translation based on the English file.
There are a lot of omissions, I attach screenshots to explain better
[screenshots.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/7743993/screenshots.zip)
.
Also, it would be nice if the findbar buttons all had tooltips (next, previous, dock/undock, ...).

### CODE REVIEW

**Comment by DenB10** [comment]
I have made a number of additions in line with my previous comment. I am passing them on to you
[messages.txt](https://github.com/ssborbis/ContextSearch-web-ext/files/7745695/messages.txt)
...

**Comment by ssborbis** [comment]
Thanks, as always.

**Comment by ssborbis** [comment]
I've sent the bulk of the changes to the dev branch. Made a few changes to your messages.json due to a few variables being renamed. I have more to do, but it's a good start. Whew, those advanced options descriptions were a bear.  Thanks again for all your hard work. I'll keep this request open until I get the rest taken care of, then cancel, as the changes are going to the other branch and I don't know how to redirect them.

**Comment by ssborbis** [comment]
I'm getting pretty close to a new release. I didn't know if you wanted to check the latest dev branch push and update your translations before I make it official. I think I've gotten most hardcoded strings moved to message.json now.

**Pull request closed without merging**
